name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Debug: list repo files and sys.path
        run: |
          python - <<'PY'
          import os, sys
          from pathlib import Path
          print("CWD:", os.getcwd())
          print("Top-level files:")
          for p in sorted(Path('.').iterdir()):
              print(" -", p)
          print("\nFirst 8 sys.path entries:")
          for i, s in enumerate(sys.path[:8]):
              print(i, s)
          PY

      - name: Run tests (set PYTHONPATH to repo root)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          echo "PYTHONPATH=$PYTHONPATH"
          pytest -q
